export const ADD_DECK = 'ADD_DECK'
export const ADD_DECK_DATA = 'ADD_DECK_DATA'
export const ADD_QUESTION = 'ADD_QUESTION'
export const DELETE_DECK = 'DELETE_DECK'
export const RECEIVE_DECKS = 'RECEIVE_DECKS'